version: 2
registries:
  rubygems-server-github-packages:
    type: rubygems-server
    url: https://rubygems.org/
    token: ${{ secrets.EMPTY_STRING }}

updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  schedule:
    interval: daily
    time: "06:00"
    timezone: Pacific/Auckland
  labels:
  - dependencies
  - go
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  registries:
  - rubygems-server-github-packages
