AllCops:
  Exclude:
    - 'lib/generators/templates/module_template.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Layout/ArgumentAlignment:
  Enabled: false

Metrics/ModuleLength:
  Max: 150
